// Workflow Engine HTTP API.
//
//	@title			Workflow Engine API
//	@version		1.0
//	@description	Multi-tenant workflow engine (projects and workflow definitions).
//	@description	Runs: POST /workflows/{id}/runs creates a pending run and step runs. Execution is done by the separate cmd/worker binary, not this HTTP server.
//	@description	Step types (field type): delay (config seconds), http_request (method, url, optional headers, body). Optional retry.max_attempts and retry.backoff_seconds (exponential backoff with jitter; 4xx except 429 are not retried).
//	@description	Chaining: in config strings use {{steps.N.output.path}} with workflow step_index N and a dotted path into that step JSON output.
//	@description	Regenerate OpenAPI: go generate ./cmd/api/...
//
//	@host		localhost:8080
//	@BasePath	/
//	@schemes	http
//
//	@securityDefinitions.apikey	ApiKeyAuth
//	@in							header
//	@name						Authorization
//	@description				Use: Bearer wf_yourPrefix.yourSecret
package main

//go:generate go run github.com/swaggo/swag/cmd/swag@v1.16.6 init -g main.go -o ../../docs -d .,../../internal/interfaces/http,../../internal/infrastructure/db/models --parseInternal

import (
	"context"
	"log"
	"log/slog"
	"net/http"
	"os"
	"os/signal"
	"strings"
	"syscall"
	"time"

	"github.com/SheykoWk/workflow-engine/internal/app"
	"github.com/SheykoWk/workflow-engine/internal/app/executor"
	"github.com/SheykoWk/workflow-engine/internal/app/ports"
	"github.com/SheykoWk/workflow-engine/internal/infrastructure/db"
	"github.com/SheykoWk/workflow-engine/internal/infrastructure/eventstore"
	kafkainfra "github.com/SheykoWk/workflow-engine/internal/infrastructure/kafka"
	httpapi "github.com/SheykoWk/workflow-engine/internal/interfaces/http"
	"github.com/joho/godotenv"

	_ "github.com/SheykoWk/workflow-engine/docs" // OpenAPI spec generated by swag (see docs.go).
)

func main() {
	if _, err := os.Stat(".env"); err == nil {
		if err := godotenv.Load(); err != nil {
			log.Fatalf("load .env: %v", err)
		}
	}

	logger := slog.New(slog.NewJSONHandler(os.Stdout, &slog.HandlerOptions{Level: slog.LevelInfo}))

	databaseURL := os.Getenv("DATABASE_URL")
	if databaseURL == "" {
		log.Fatal("DATABASE_URL is required")
	}

	sqlDB, err := db.OpenSQL(context.Background(), databaseURL)
	if err != nil {
		log.Fatalf("database: %v", err)
	}
	defer func() { _ = sqlDB.Close() }()

	workflowRepo := db.NewWorkflowRepository(sqlDB)
	workflowSvc := app.NewWorkflowService(workflowRepo)
	projectRepo := db.NewProjectRepository(sqlDB)
	apiKeyRepo := db.NewAPIKeyRepository(sqlDB)
	stepRunRepo := db.NewStepRunRepository(sqlDB)
	triggerRepo := db.NewEventTriggerRepository(sqlDB)
	workflows := httpapi.NewWorkflowHandler(workflowSvc)
	projects := httpapi.NewProjectHandler(projectRepo)

	// Optional: Event Streaming backbone integration.
	var publisher ports.EventPublisher
	if esURL := os.Getenv("EVENT_STREAMING_BASE_URL"); esURL != "" {
		publisher = eventstore.NewHTTPClient(esURL, os.Getenv("EVENT_STREAMING_API_TOKEN"), logger)
		logger.Info("event publishing enabled", "url", esURL)
	}

	executorCtx, stopExecutor := context.WithCancel(context.Background())
	defer stopExecutor()
	executor.Start(executorCtx, stepRunRepo, publisher, logger)
	log.Printf("executor: started")

	// Optional: Kafka consumer for event-driven workflow triggers.
	kafkaBrokers := os.Getenv("KAFKA_BROKERS")
	kafkaTopic := os.Getenv("KAFKA_EVENTS_TOPIC")
	if kafkaBrokers != "" && kafkaTopic != "" {
		triggerSvc := app.NewEventTriggerService(triggerRepo, workflowRepo, logger)
		consumer := kafkainfra.NewConsumer(kafkainfra.Config{
			Brokers: strings.Split(kafkaBrokers, ","),
			Topic:   kafkaTopic,
			GroupID: envOrDefault("KAFKA_CONSUMER_GROUP", "workflow-engine"),
		}, triggerSvc.Handle, logger)

		consumerCtx, stopConsumer := context.WithCancel(context.Background())
		defer stopConsumer()
		go func() {
			logger.Info("kafka consumer started", "topic", kafkaTopic, "brokers", kafkaBrokers)
			if err := consumer.Run(consumerCtx); err != nil {
				logger.Error("kafka consumer exited with error", "error", err)
			}
			_ = consumer.Close()
		}()
	}

	addr := envOrDefault("HTTP_ADDR", ":8080")
	handler := httpapi.NewRouter(apiKeyRepo, workflows, projects)
	srv := &http.Server{
		Addr:    addr,
		Handler: handler,
	}

	go func() {
		log.Printf("listening on %s", addr)
		if err := srv.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			log.Fatalf("server: %v", err)
		}
	}()

	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	<-quit
	log.Printf("shutting down server...")

	shutdownCtx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	if err := srv.Shutdown(shutdownCtx); err != nil {
		log.Printf("server shutdown: %v", err)
	}
	log.Printf("server stopped")
}

func envOrDefault(key, fallback string) string {
	if v := os.Getenv(key); v != "" {
		return v
	}
	return fallback
}
